basePath: /
consumes:
    - application/json
definitions:
    BindingAttribute:
        properties:
            Type:
                type: string
            Value:
                type: string
        type: object
        x-go-package: github.com/Knox-AAU/DatabaseLayer_Server/pkg/graph
    Result:
        properties:
            query:
                type: string
                x-go-name: Query
            triples:
                items:
                    $ref: '#/definitions/Triple'
                type: array
                x-go-name: Triples
        type: object
        x-go-package: github.com/Knox-AAU/DatabaseLayer_Server/pkg/http/rest
    Triple:
        properties:
            o:
                $ref: '#/definitions/BindingAttribute'
            p:
                $ref: '#/definitions/BindingAttribute'
            s:
                $ref: '#/definitions/BindingAttribute'
        title: Triple requires the json tags to match with the queries that are used to retrieve it.
        type: object
        x-go-package: github.com/Knox-AAU/DatabaseLayer_Server/pkg/graph
host: localhost:8080
info:
    description: This repository implements a server to facilitate communication on the KNOX pipeline.
    title: Database Layer Server API.
    version: 0.0.1
paths:
    /get:
        get:
            description: |-
                Example query: {{url}}/get?p=x&p=y&so=x&so=y
                To query the whole graph, leave all parameters empty.
            operationId: get
            parameters:
                - description: Subject or Object
                  in: query
                  items:
                    type: string
                  name: so
                  type: array
                - description: Predicate
                  in: query
                  items:
                    type: string
                  name: p
                  type: array
            produces:
                - application/json
            responses:
                "200":
                    description: filtered triples response
                    schema:
                        items:
                            $ref: '#/definitions/Result'
                        type: array
            summary: This endpoint allows for querying with filters.
            tags:
                - get
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
