# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches-ignore:
      - "main" 

env:
  VIRTUOSO_SERVER_URL: ${{ secrets.VIRTUOSO_SERVER_URL }}

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      virtuoso:
        image: openlink/virtuoso-opensource-7:latest
        env:
          DBA_PASSWORD: qzu49svh
        ports:
          - 1111:1111
          - 8890:8890
        options: --name knox_virtuoso_db --volume "${{ github.workspace }}/knox_virtuoso_db:/database"

    steps:
      - name: Set permissions for virtuoso db directory
        run: sudo chmod -R 777 ${{ github.workspace }}/knox_virtuoso_db || true
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Run Go Tests
        run: go test ./...
